### ISSUE TITLE
Use of dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by thesublimeobject** [amine-benselim/wp-react-redux#2]
Is there any specific reason why you seem to use the following

`<h3 dangerouslySetInnerHTML={{ __html: post.title.rendered }} />`

rather than `<h3>{ post.title.rendered }</h3>`.

Just curious. It's been about six months since I actively worked on a React project, but I don't know if any advantages. If I am wrong, please correct me.

**Comment by aminbenselim** [comment]
the reason is because i thought the title might have some html tags or html entities. `<h3>{post.title.rendered}</h3>` would render it as a string

**Comment by thesublimeobject** [comment]
I guess that makes sense. Just genuinely curious.
